### PR TITLE
Fixed scrolling when verticalScrollHeight is 0

### PR DESCRIPTION
**Pull request by 500tech-user**
Open the basic example:
http://ui-grid.info/docs/#/tutorial/101_intro
Hover above the grid and try to scroll up - it doesn't scroll the page.
Scrolling down, however, works.

This fixes it

### CODE REVIEW

**Comment by tuhoojabotti** [comment]
Duplicates: #3666 #3531 #3340 (for reference)

**Comment by swalters** [comment]
@500tech-user Can you tell me is this still an issue in master?  I think this was fixed in some other commits.

**Comment by swalters** [comment]
ok, I see that mousewheel is still broken for it

**Comment by swalters** [comment]
Thanks for PR.

Rather than putting the logic where you have it, we would rather see the verticalScrollLength property added to scrollEvent and then the atBottom, atTop, atLeft, and atRight can use that number to determine if it is at bottom, top, etc.

I'll look at making this change and will close this PR when complete.

**Comment by swalters** [comment]
Should be fixed with
https://github.com/angular-ui/ng-grid/commit/e582174a826bb232ddbb4fda8001b64c3273df0d .  Thanks for the PR

**Comment by 500tech-user** [comment]
Awesome
BTW, I also noticed that when zooming in or out the calculation is wrong.
Did you ever encounter that?

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/> - Web and Mobile development
- hackademy.co.il <http://hackademy.co.il/angularjs/about> - AngularJS,
Ruby on Rails training
- (+972) 52 747 5633

**Comment by rhrasna** [comment]
The problem persists in v.3.0.1.

**Pull request closed without merging**
