### PR TITLE
Scrollbar placeholder

### PR DESCRIPTION
**Pull request by swalters**
Adds a placeholder element to the bottom of the left and right containers.  Makes the viewport for those containers shorter to allow for placeholder.

We still have an issue when using mousewheel and scrolling to the bottom in any container other than the container that has the vertical scrollbar. This can easily bee seen on 401 tutorial.  Pin something to the right and use the mousewheel to scroll the last few rows on left or body container.  You will never get the last few rows.  I'm hoping @c0bra can help fix.

[Review on Reviewable](https://reviewable.io/reviews/angular-ui/ng-grid/3769)

### CODE REVIEW

**Comment by swalters** [comment]
Please wait to merge until I can fix the NoScrollBar scenarios.

**Comment by swalters** [comment]
@c0bra it's ready for a merge

**Comment by c0bra** [comment]
I'm trying to take a look but I'm uncertain if any quirks I encounter are related to this PR or not.

One thing I noticed is that if I enter "deep edit" mode and then try to tab after editing it goes to the first element on the page rather than whatever it should do.

**Comment by swalters** [comment]
@c0bra what tutorial are you seeing this behavior?  On my local box, it works fine in 401 tutorial

**Comment by c0bra** [comment]
On tutorial 201. I'm on Win7 Chrome. You?

**Comment by swalters** [comment]
201 doesn't use CellNav :)  you won't get any tabbing or enter key out of it

**Comment by c0bra** [comment]
Well it's sort of silly for me to suggest that there's a bug, then isn't it??

**Comment by c0bra** [comment]
Looks great, @swalters. I say merge it.

**Pull request merged**
