### PR TITLE
Add registerColumnsProcessor to API

### PR DESCRIPTION
**Pull request by genu**
I also introduced the priority for the processor.

Followed the same style as `registerRowsProcessor(...)` method

Related to #3251

### CODE REVIEW

**Comment by PaulL1** [comment]
Seems to have failed a number of unit tests.....

**Comment by genu** [comment]
sorry, I took a shot in the dark there. I cant seem to run the tests locally for some reason.

I get this:

screen shot 2015-04-09 at 7 54 19 pm

I'll looking to fix this.

**Comment by PaulL1** [comment]
Probably that's the e2e tests.  You can run with:
`grunt dev --no-e2e --angular=1.3.0`

which works in most instances.

**Comment by genu** [comment]
There seems to be an issue, I think with #3211. 3 Specs fail after that build.

**Comment by PaulL1** [comment]
OK, that PR was passing all the tests when I merged it.  I can take a look though.

**Comment by PaulL1** [comment]
I've fixed those tests in master - you can potentially merge master down again, and then squash the commits and we're good to merge.

**Pull request merged**
