### PR TITLE
make rowRenderIndex available to GridRow

### PR DESCRIPTION
**Pull request by tx-tim**
I am looking to do something similar to issue #2958 but I want the rowIndex to be made available during the compile phase.
If there's a better way to do this I am 100% open to suggestions.

### CODE REVIEW

**Comment by PaulL1** [comment]
I haven't looked all the way through the code, but I've seen lots of problems in the past with render indexes because of row virtualisation.  Are you across that, and are you sure renderIndex is the right thing to have access to v's the index in the visibleRowsCache or something else?

**Comment by tx-tim** [comment]
Well, another way would be to pass $index as part of the isolate scope from the renderedRows repeater in uiGridViewport.html.  I don't really see what that would buy you because it's only iterating over renderedRows.  Something like so:

    <div ng-repeat="(rowRenderIndex, row) in rowContainer.renderedRows track by $index" class="ui-grid-row" ng-style="Viewport.rowStyle(rowRenderIndex)">
      <div ui-grid-row="row" row-render-index="rowRenderIndex" row-actual-index=$index></div>
    </div>

What do you think?

**Comment by PaulL1** [comment]
It depends what you're trying to achieve.  As per the issue you reference, and the FAQ, there are a few different things an index can be:

 - a number we allocate to the data that never changes even when we sort/filter.  In that case, we want the position in the data array
 - a number we display on the screen sort of like the row number in Excel - when we resort it changes, but when we filter we get gaps in the number.  This we don't really have - we don't have a "all rows sorted but not filtered" array anywhere
 - a number that is just the number in the currently visible rows, in the current order they're showing on the screen.  This would be the position in the visibleRows cache
 - a number that is the render index of the currently rendered DOM elements (so if we have 1000 rows and we're sort of half way through, then our renderIndex might be 7 or 8 if we were the 4th row down the screen - there's usually 4 rows rendered off-screen).  In other words - this number is usually completely useless for anything

If we're going to push it into the base we need to be really clear what the renderIndex actually is, and what it can safely be used for.  I've seen a number of people tripped up by putting one in and then discovering it never goes higher than about 20, because we usually don't render more than about 20 rows.

**Comment by tx-tim** [comment]
You are so right!  Which is probably why the functionality doesn't already
exist.  Ok - thanks for talking this over with me - I'll look at the code
some more.

**Pull request closed without merging**
