### PR TITLE
Updating the Persian Translation.

### PR DESCRIPTION
**Pull request by salarmehr**
[Review on Reviewable](https://reviewable.io/reviews/angular-ui/ng-grid/3842)

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
Travis's errors:
```
src/js/i18n/fa.js
  line 19  col 29  This character may get silently deleted by one or more browsers.
  line 21  col 23  This character may get silently deleted by one or more browsers.
  line 23  col 21  This character may get silently deleted by one or more browsers.
  line 24  col 25  This character may get silently deleted by one or more browsers.
  line 28  col 21  This character may get silently deleted by one or more browsers.
  line 36  col 22  This character may get silently deleted by one or more browsers.
  line 51  col 24  This character may get silently deleted by one or more browsers.
  line 53  col 44  This character may get silently deleted by one or more browsers.
  line 54  col 43  This character may get silently deleted by one or more browsers.
  line 55  col 44  This character may get silently deleted by one or more browsers.
  line 56  col 44  This character may get silently deleted by one or more browsers.
  line 57  col 43  This character may get silently deleted by one or more browsers.
  line 58  col 44  This character may get silently deleted by one or more browsers.
  line 62  col 63  This character may get silently deleted by one or more browsers.
  line 73  col 22  This character may get silently deleted by one or more browsers.
  line 74  col 28  This character may get silently deleted by one or more browsers.
```
These will need to be fixed before we can merge this.

**Comment by salarmehr** [comment]
@JLLeitschuh They are notice indeed. The pointed characters are quit safe. The push can be merged safely.

**Comment by JLLeitschuh** [comment]
The travis build failed however, you will need to figure out a way to get the build to pass before we can merge it in.

**Comment by c0bra** [comment]
@salarmehr You could try saving the file as UTF-8 and running `grunt jshint` locally, or put `/* jshint -W100 */` at the top of the file.

**Comment by salarmehr** [comment]
@c0bra Merging all i18n files in the built file make it heavy. Please keep them separate. The developer can merge the needed language himself.

**Comment by c0bra** [comment]
@salarmehr Sounds like a good suggestion. You can open a separate issue for that if you want.

Also your commit includes changes to pagination.html, which you probably didn't intend. Can you fix that, rebase, and push again? Thanks.

**Comment by salarmehr** [comment]
@c0bra I'm not sure how do that. May you please shed some light on it? If possible please manually copy and paste the new fa.js file to your local repo and ignore the PRl.

**Comment by c0bra** [comment]
@salarmehr I went ahead and brought your changes in manually. Thanks for the commit!

**Pull request closed without merging**
