### PR TITLE
Feat(exporter): export all till all data loaded

### PR DESCRIPTION
**Pull request by AlphaHinex**
When using external pagination and want to use the native export function, this PR will do some help. Also see #2967 .

### CODE REVIEW

**Comment by PaulL1** [comment]
I'm OK with the concept here, but a couple of things:
1.  I think we should use a promise for the data, rather than doing a $timeout in a loop.  Usually when they request all the data from the server they'll get a promise back, so they can give us that promise (or chain onto it in a then, and give us the resulting promise), and we can just wait on that promise.  

2.  We need to squash all the commits into a single commit before merging.

**Comment by AlphaHinex** [comment]
Is it OK now? I am not familiar with promise, sorry for that.

**Comment by c0bra** [comment]
@PaulL1 any chance you couuld look at this again?

**Comment by PaulL1** [comment]
OK, there's a couple gremlins there, but I need to test it anyway, so I'll merge then update.  I'm not quite sure what the `callback` function does - I think it's not needed with the promise.  And I think in the tutorial we can directly return the $http promise rather than creating a new deferred.  But I'll run it and check.

**Comment by PaulL1** [comment]
I've updated the code a bit for some usage of deferred - I think you'd chained too many things together.

You can directly set the total items and data in the success block of the $http get, and you can return the promise from the $http rather than creating a new one.

I've tidied up a bit in the main code too - you shouldn't need the callback function, you can just put that content into a .then block.  This avoids passing around references too much.

Overall good though - thanks for the contribution.

**Comment by AlphaHinex** [comment]
Thanks for the cleanup works :satisfied:

**Comment by vijender1256** [comment]
@PaulL1 Hi paul, I am looking to implement export all data to pdf on server side paging. I dont see any code here on this page for doing this. Can you please help me to implement this functionality on UI-grid server side paging. appreciate your help.

**Comment by PaulL1** [comment]
There should be code there for export all with paging - there is a callback that is triggered that asks the programmer to get "all data", which can then be exported.

**Comment by vijender1256** [comment]
@PaulL1 I am not seeing any code on this page, can you provide me a link for the code that I can refer to. I greatly appreciate your help :)

**Comment by vijender1256** [comment]
@PaulL1 Thank you, i figured the problem , when binding the Ui-grid properties i have something like this:

 $scope.couponGridOptions = {
            data: 'CouponsList',
            enableRowSelection: true,
            enableRowHeaderSelection: false, etc...

so when i use that property "data" instead of:

  var getPageSuccess = function (result) {
            $scope.couponGridOptions.data = result.Promotions;
            $scope.couponGridOptions.totalItems = result.totalItems;
        };

explicitly loading when page is successful I am had problems.

**Comment by vijender1256** [comment]
@PaulL1 I am having trouble in resetting page number, When I am on page number 2 and I have refresh button which rebinds the ui-grid, when i do that the data is getting rebind but the page number still is 2, how do i reset the page number to 1 after i click on refresh button. Any help is appreciated, lot of people asked this question but I did not find solution. Thanks

**Comment by PaulL1** [comment]
My recollection is that you can set the page number property directly when you reset the group.

**Comment by vijender1256** [comment]
Thank you very much :)  its  $scope.yourGridOptions.paginationCurrentPage = 1; in case for anyone who is looking

**Pull request merged**
