### PR TITLE
fix for #2811

### PR DESCRIPTION
**Pull request by lvostinar**
Fix infinite scrolling when rowIdentity is used.

### CODE REVIEW

**Comment by c0bra** [comment]
This commit fails to pass the style check, please address that. Also, please put text in your pull request description.

**Comment by lvostinar** [comment]
Done.

**Comment by c0bra** [comment]
@lvostinar I'll check this out locally and get it merged. Do I just need to use infinite scroll with my own custom rowIdentity to cause the problem to occur? What problem/error should I expect to happen? I would like to get a unit test written for it if I can.

**Comment by lvostinar** [comment]
I was getting a lot of flickering because rowIndex was always set to 0.

**Comment by jcompagner** [comment]
yes we have our own rowIdent function that returns a unique id that we already know like this:

					rowIdentity: function(o) {
						return o._svyRowId;
					},
					rowEquality: function(row1,row2) {
						return row1._svyRowId == row2._svyRowId; 
					}

so our rows don't really have a $$hashKey because that is not really generated. we provide our own.
But that code doesn't use our rowIdentity function that we provide but depends on that hashKey thats why it never hit, and the range that we try to calculate there was never done correctly

**Comment by jcompagner** [comment]
It is not fully clear to me how getRowIdentity and the rowIdentty really work
We implement the rowIdentity (that use used a lot for example in the RowHashMap class/object)

But getRowIdentity() is only use in  Grid.prototype.modifyRows function
We don't hit that code because for us self.options.useExternalSorting is true so it always goes into the first if of that modifyRows function.
Thats why for use the $$hashKey is really never generated (and i guess if we didn't have externalSorting enabled we also had to provide also the getRowIdentity which then does the same as rowIdentity?

**Comment by c0bra** [comment]
I'm just going to go ahead and merge this.

**Pull request merged**
